package credit;
/*
 *
 * Author: George Kelly 
 * Student Number: 18037010
 * A program to verify 16 digit credit card and 10 digit ISBN numbers
 * 
 */
public class Credit extends javax.swing.JFrame {
    public Credit() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldInput = new javax.swing.JTextField();
        txtFieldOutput = new javax.swing.JTextField();
        btnIsbn = new javax.swing.JButton();
        btnCredit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFieldInput.setToolTipText("");
        txtFieldInput.setName(""); // NOI18N
        txtFieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldInputActionPerformed(evt);
            }
        });

        btnIsbn.setText("Verify ISBN");
        btnIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsbnActionPerformed(evt);
            }
        });

        btnCredit.setText("Verify Credit Card");
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCredit))))
                    .addComponent(txtFieldOutput))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIsbn))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCredit)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(txtFieldOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldInputActionPerformed
        // TODO add your handling code her
        
    }//GEN-LAST:event_txtFieldInputActionPerformed

    // Function to clear input and output text fields
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtFieldInput.setText("");
        txtFieldOutput.setText("");

    }//GEN-LAST:event_btnClearActionPerformed
    
    // Function to handle button for ISBN checking
    private void btnIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsbnActionPerformed
        // TODO add your handling code here:
        isbn_check();
    }//GEN-LAST:event_btnIsbnActionPerformed

    
    // Function to handle button for credit card checking
    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
        credit_check();
    }//GEN-LAST:event_btnCreditActionPerformed
    
    // Function to verify 16 digit long credit card numbers
    // Using Luhns algortihm
    private void credit_check(){
        String s = txtFieldInput.getText(); 
        
        // Validating user input for credit card number
        // Card number must be 16 digits long
        if(s.length() != 16){
            txtFieldOutput.setText("Error: Credit Card number must be 16 digits long. ");
            return;
        }
        
        // Loop through all digits from user input
        // Parsing each character as an integer
        // Result from performing Luhn's algorithm is stored in num variable
        int num = 0;
        for (int i = 0, n = s.length(); i < n; i++){
            try {
                int x = Integer.parseInt(String.valueOf(s.charAt(i)));          
                if ((i+1) % 2 == 1){
                    x = x * 2;
                    if (x >= 10) num += x - 9;
                    else num += x;
                }
                else {
                    num += x;
                }   
            }
            // If unable to parse character as an integer, throw exection and return
            catch (Exception e) {
                txtFieldOutput.setText("Error: All digits must be numeric. ");
                return;
            }       
        }
        
        // If the resuliting value from performing Luhn's algorithm is not 
        // Evenly divisble by 10 then the card number is invalid
        // Set output text field accordingly
        if (num % 10 != 0) txtFieldOutput.setText("Invalid");
        else txtFieldOutput.setText("Valid");
    }
    
    // Function to check ISBN number using weighted sum
    private void isbn_check(){
        int[] d = new int[10];
       
        String s = txtFieldInput.getText();
        // Validating user input
        // ISBN number must be 10 digits long
        if (s.length() != 10){
            txtFieldOutput.setText("Error: ISBN number must be 10 digits long. ");
            return;
        }
        
        int num = 0;
        for (int i = 0, n = s.length(); i < n ; i++){
            if (s.charAt(i) == 'X' ) num = num + ((i+1) * 10);
            else {
                d[i]= Integer.parseInt(String.valueOf(s.charAt(i)));
                num = num + ((i+1) * d[i]);
            }                  
        }
        // If weighted sum is evenly divisible by 11, then the 
        // ISBN number is valid
        // Set output text field accordingly
        if (num % 11 == 0) txtFieldOutput.setText("Valid");
        else txtFieldOutput.setText("Invalid");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnIsbn;
    private javax.swing.JTextField txtFieldInput;
    private javax.swing.JTextField txtFieldOutput;
    // End of variables declaration//GEN-END:variables
}
